
const ActionType = {
  LOAD_PAGE_REQUEST: 'LOAD_PAGE_REQUEST',
  LOAD_SITE_REQUEST: 'LOAD_SITE_REQUEST',
  LOAD_SITE_PAGES_REQUEST: 'LOAD_SITE_PAGES_REQUEST',
  SWITCH_PAGE: 'SWITCH_PAGE',
  TOGGLE_MENU: 'TOGGLE_MENU',
  CLOSE_MENU: 'CLOSE_MENU',
};

export default ActionType;
